export const routeConfig = {
  home: '/',
  signIn: '/signIn',
  logIn: '/logIn',
  wishList: '/wishList',
  cart: '/cart',
  checkOut: '/cart/checkOut',
  account: '/account',
  about: '/about',
  profile: '/account/profile',
  myOrders: '/account/orders',
  addressBook: '/account/address_book',
  paymentOptions: '/account/payment_options',
  returns: '/account/returns',
  cancellations: '/account/cancellations',
  reviews: '/account/reviews',
  contact: '/contact',
  productList: 'products',
  productDetails: '/product/:productId',
  shop: '/shop',
  womansFashion: '/womans_fashion',
  mensFashion: '/mens_fashion',
  electronics: '/electronics',
  medicine: '/medicine',
  sportOutdoor: '/sport_&_outdoor',
  babyToys: '/baby_&_toys',
  groceriesPets: '/groceries_&_pets',
  healthBeauty: '/health_&_beauty',
  allProducts: '/all_products',
  privacyPolicy: '/privacy_policy',
  termsOfUse: '/terms_of_use',
  faq: '/faq',
  subscribe: '/subscribe',
  // 404 page
  error: '*'
};
